version: '3'

services:
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "db"
    ports:
      - 8080:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "user"
      MYSQL_ROOT_PASSWORD: "db"

  metaflop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9292:9292
    volumes:
      - .:/metaflop
    depends_on:
      - db
    links:
      - db:db

volumes:
  db_data: